version: '3'

services:
  playground:
    container_name: e2e-playground
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  database:
    container_name: e2e-database
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USERNAME: core
      MONGO_INITDB_PASSWORD: core
      MONGO_INITDB_DATABASE: core
    ports:
      - '27017:27017'
    volumes:
      - ../docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
