name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & start docker containers
        run: cd e2e && docker compose up -d --build
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Run cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
          browser: chrome
