name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start Docker Compose
        run: docker-compose up -d --build
      - name: Show log from api-gateway
        run: docker logs "api-gateway"
      # Install pnpm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run dev:prepare && cd e2e && pnpm build
          start: docker compose up -d && cd e2e && pnpm start
          browser: chrome
        env:
          # overwrite commit message sent to Cypress Cloud
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
