name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start Docker Compose
        run: docker compose up -d
#      - name: Show log from docker
#        run: docker compose logs
        # Install pnpm dependencies, cache them correctly
        # and run all Cypress tests
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup playground
        run: pnpm i --frozen-lockfile && pnpm dev:prepare
      - name: Setup e2e
        run: cd ./e2e && pnpm i
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: e2e
          install: false
          browser: chrome
        env:
          # overwrite commit message sent to Cypress Cloud
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
